Shilpi newcastle brca training
publichealthengland/data_management_system pull request #389
Opened 2022-07-19 16:28 UTC by shilpigoeldev

I have completed changes for Newcastle BRCA , adhering to the final rules and Francesco has signed off QA .

2022-07-20 06:52 UTC, ollietulloch requested changes
Thanks @shilpigoeldev, looks good.

Just some additional whitespace in the bash script.

Also are the `_deprecated.rb` versions on the handler and persister still needed?

2022-07-20 06:52 UTC, ollietulloch commented on lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
> +RTD () {
Is this just additional whitespace?

2022-07-20 10:37 UTC, shilpigoeldev commented on lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
> +RTD () {
Hi Ollie, I have removed it now.

2022-07-20 10:39 UTC, shilpigoeldev commented
I have removed the extra space and extra files for Newcastle in repo. Have re-run the counts and tests to ensure no impact of removing the deprecated files. Thank you Ollie 🙏

2022-07-21 09:25 UTC, ollietulloch approved these changes
Thanks for the updates

2022-07-21 09:28 UTC, merged

2022-07-21 09:28 UTC, shilpigoeldev commented
Thanks Ollie, its all done now and merged inn main develop branch !!