Shilpi brca liverpool
publichealthengland/data_management_system pull request #412
Opened 2022-08-16 16:33 UTC by shilpigoeldev

Liverpool BRCA handler is done , and Fiona has signed off QA. Kindly review ..Thanks 🙏

2022-08-16 18:55 UTC, ollietulloch commented on lib/import/brca/providers/liverpool/liverpool_handler.rb
> +          def add_organisationcode_testresult(genotype)
@shilpigoeldev I'm not sure this needs to be it's own method. I think it's only used once, and is a single line.

2022-08-16 19:11 UTC, ollietulloch requested changes
Hi @shilpigoeldev,

A couple of small tweaks. I've also noticed that we define `build_raw_record` in every test class, that should be added to a test helper.

Thanks

2022-08-17 11:52 UTC, shilpigoeldev commented on test/lib/import/brca/providers/liverpool/liverpool_handler_test.rb
> +    assert_equal true, @handler.abnormal?(@genotype)
Thanks Ollie, done the changes .

2022-08-17 11:53 UTC, shilpigoeldev commented on lib/import/brca/providers/liverpool/liverpool_handler.rb
> +            genotype.attribute_map['organisationcode_testresult'] = '69810'
I have now moved it to main `process_fields` method .

2022-08-17 11:53 UTC, shilpigoeldev commented on test/lib/import/brca/providers/liverpool/liverpool_handler_test.rb
> +    assert_equal true, @handler.abnormal?(@genotype)
Done ✅

2022-08-17 11:53 UTC, shilpigoeldev commented on test/lib/import/brca/providers/liverpool/liverpool_handler_test.rb
> +
Done ✅

2022-08-17 11:55 UTC, shilpigoeldev commented on test/lib/import/brca/providers/liverpool/liverpool_handler_test.rb
> +  def build_raw_record(options = {})
I agree, will create a separate branch to move this method build_raw_record one level up to
 module ActiveSupport
  class TestCase
and will modify all handlers test class consistently across all.

2022-08-17 11:56 UTC, ollietulloch commented on test/lib/import/brca/providers/liverpool/liverpool_handler_test.rb
> +  def build_raw_record(options = {})
As dicussed with @shilpigoeldev, this will be tackled in a separate PR across all handler tests

2022-08-17 12:35 UTC, ollietulloch approved these changes
Thanks @shilpigoeldev 

Rubocop error is an existing error

2022-08-17 12:41 UTC, merged

2022-08-17 12:41 UTC, shilpigoeldev commented
Merged into develop.