Germline naming
publichealthengland/data_management_system pull request #426
Opened 2022-09-22 15:09 UTC by shilpigoeldev

Have corrected rubocop issues which were straightforward and not needed logic/code rewriting (not in scope of this work) .

2022-09-29 16:30 UTC, FrancescoNea approved these changes
All tests pass. I have added disablers for some Rubocop complaints.
These complaints are mostly about classes, couple of methods and some lines being too long.
As I think that, for the moment being, these complaints are low priority, I am happy to approve this PR.

2022-09-30 12:23 UTC, ollietulloch requested changes
Hi @shilpigoeldev ,

A couple of things to adjust for rubocop, please see comments. I realise that these are inherited issues from existing code, but it'd be good to take the chance to fix them.

Thanks,
Ollie

2022-09-30 12:23 UTC, ollietulloch commented on lib/import/utility/extraction_utilities.rb
> +        LOCATION_REGEX = /(#{GENE_LOCATION}(?: in (?:brca(?:1|2) )?#{EXON_LOCATION})?|#{EXON_LOCATION})/i
@shilpigoeldev could you look at using the `/x` modifier to split the regexp over multiple lines? [Example here](https://stackoverflow.com/questions/3762183/split-ruby-regex-over-multiple-lines).

There are additional lines in this file that should also be corrected

2022-09-30 12:23 UTC, ollietulloch commented on lib/import/germline/genotype.rb
> +      def similar_record(other_genotype, field_list, strict = true)
Please ue kwargs when defining method with boolean argument - [example here](https://stackoverflow.com/questions/67391214/style-optionalbooleanparameter-use-keyword-arguments-when-defining-method-with)

Remember to change all calls of this method

2022-09-30 12:23 UTC, ollietulloch commented on lib/import/utility/extraction_utilities.rb
> +        def initialize(write_csv = false)
Please ue kwargs when defining method with boolean argument - [example here](https://stackoverflow.com/questions/67391214/style-optionalbooleanparameter-use-keyword-arguments-when-defining-method-with)

Remember to change all calls of this method

2022-10-05 10:09 UTC, shilpigoeldev commented
@ollietulloch I have now worked on the review comments and rematched the counts , thank you 🙏

2022-10-05 13:36 UTC, merged